export const LIST_TYPE = {
  DASHBOARD_LIST: 1,
  CUSTOMER_LIST: 2,
  CATEGORIES_LIST: 3,
  MENU_LIST: 4,
  ADD_ONS: 5,
  TABLE_LIST: 6,
  REDEEM_MENU_LIST: 7,
  CUSTOMER_DETAILS: 8,
  COMBO_MENU: 9,

  SHOP_LIST:10,
  SHOP_ITEM_LIST:11
};
